FROM golang:1.22.5

# All dependencies required to build the Go project
RUN apt-get update && apt-get install -y curl build-essential sudo

RUN curl https://sh.rustup.rs/ -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY go.sum go.mod ./
RUN go mod download

COPY config/maps.json config/maps.json
COPY internals internals
COPY pkg pkg
COPY dashes/beacon/maps dashes/beacon/maps
COPY cmd/beacon/tester/main.go main.go

RUN go build -o tester .
