version: '3'

tasks:
  default:
    desc: Run the project
    cmds:
      - task beacon
      - ./beacon
      - defer: rm beacon

  beacon:
    desc: Build the beacon project
    cmds:
      - go build -o beacon cmd/beacon/beacon/main.go

  beacon-tester:
    desc: Build the beacon project tester (just for development)
    cmds:
      - go build -o tester cmd/beacon/tester/main.go

  marvin:
    desc: Build the marvin project
    cmds:
      - go build -o marvin cmd/marvin/marvin/main.go

  marvin-tester:
    desc: Build the marvin project tester (just for development)
    cmds:
      - go build -o tester cmd/marvin/tester/main.go

  clean:
    desc: Clean up the repository
    cmds:
      - rm -f app.log marvin beacon tester
      - rm -f open_results.json rookie_results.json
      - rm -rf dashes/marvin/repos/*
      - rm -rf dashes/marvin/traces/*
      - rm -rf dashes/beacon/repos/*
      - rm -rf dashes/beacon/traces/*
      - rm -rf bin

  delete-repos:
    desc: Remove the organization repositories (use with caution)
    cmds:
      - go run scripts/delete_repos/main.go

  test:
    desc: Run all the tests
    cmds:
      - go test -count=1 ./internals/grader/rookie
      - go test -count=1 ./internals/grader/open
      - task: clean

    help:
      silent: true
      desc: Display available commands
      cmds:
        - echo "run          - Build and run the project"
        - echo "build        - Compile the project"
        - echo "build-tester - Compile the tester (for development)"
        - echo "build-docker - Rebuild the Docker image"
        - echo "clean        - Clean the project environment"
        - echo "clean-repos  - Remove the organization repositories (use with caution)"
        - echo "test         - Execute all tests"
        - echo "help         - Display this help message"
