version: '3'

tasks:
  default:
    desc: Run the project
    cmds:
      - task run

  run:
    desc: Run the project after building
    cmds:
      - task: build
      - defer: rm -f dashinette
      - ./dashinette

  build:
    desc: Build the project
    cmds:
      - go build -o dashinette main.go

  build-tester:
    desc: Build the project
    cmds:
      - go build -o tester cmd/tester/main.go

  build-docker:
    desc: Rebuild the Docker image
    cmds:
      - docker build -t dashinette-tester .

  clean:
    desc: Clean the project
    cmds:
      - rm -f dashinette tester
      - rm -rf dashes/marvin/repos/*
      - rm -rf dashes/marvin/traces/*
      - rm -rf open_results.json rookie_results.json

  clean-repos:
    desc: Remove the organization repositories
    cmds:
      - go run scripts/delete_repos/main.go

  test:
    desc: Run all the tests
    cmds:
      - go test -count=1 ./internals/grader/rookie
      - go test -count=1 ./internals/grader/open
      - task: clean

  help:
    silent: true
    desc: Show this help message
    cmds:
      - echo "run          - build and run the project"
      - echo "build        - build the project"
      - echo "build-tester - build the tester (just for development)"
      - echo "build-docker - rebuild the Docker image"
      - echo "clean        - clean the project"
      - echo "clean-repos  - remove the organization repositories"
      - echo "test         - run all the tests"
      - echo "help         - show this help message"
