version: '3'

tasks:
  default:
    desc: Run the project
    cmds:
      - task run

  run:
    desc: Run the project after building
    cmds:
      - task: build
      - defer: { task: clean }
      - ./dashinette

  build:
    desc: Build the project
    cmds:
      - go build -o dashinette main.go

  clean:
    desc: Clean the project
    cmds:
      - rm -f dashinette

  fclean:
    desc: Deletes the cloned repositories and generated traces
    cmds:
      - rm -rf repo/*
      - rm -rf traces/*

  clean-repos:
    desc: Remove the organization repositories
    cmds:
      - go run scripts/deleteRepos.go

  test-grader:
    desc: Run the tests
    cmds:
      - go test ./internals/grading

  test-all:
    desc: Run all the tests
    cmds:
      - task: test-grader

  help:
    silent: true
    desc: Show this help message
    cmds:
      - echo "build - build the project"
      - echo "run - build and run the project"
      - echo "clean - clean the project"
      - echo "clean-repos - remove the organization repositories"
      - echo "help - show this help message"
