version: '3'

tasks:
  default:
    desc: Run the project
    cmds:
      - task run

  run:
    desc: Run the project after building
    cmds:
      - task: build
      - defer: rm -f dashinette
      - ./dashinette

  build:
    desc: Build the project
    cmds:
      - go build -o dashinette main.go

  build-tester:
    desc: Build the project
    cmds:
      - go build -o tester cmd/tester/main.go

  build-docker:
    desc: Rebuild the Docker image
    cmds:
      - docker build -t dashinette-tester .

  clean:
    desc: Clean the project
    cmds:
      - rm -f dashinette
      - rm -rf repo/*
      - rm -rf traces/*

  clean-repos:
    desc: Remove the organization repositories
    cmds:
      - go run scripts/delete_repos/main.go

  test:
    desc: Run all the tests
    cmds:
      - go test -count=1 ./internals/grader/rookie
      - go test -count=1 ./internals/grader/open

  help:
    silent: true
    desc: Show this help message
    cmds:
      - echo "build - build the project"
      - echo "run - build and run the project"
      - echo "clean - clean the project"
      - echo "clean-repos - remove the organization repositories"
      - echo "help - show this help message"
